### ISSUE TITLE
UI component to show disappearing messages

### ISSUE THREAD

**Issue by UrAvgDeveloper** [fetchai/fetch-wallet#178]

**Comment by StephenBrownFetch** [comment]
https://www.figma.com/file/IV8jniew1G3fiAUv1JYxNh/Fetch.ai-Wallet-Extension?node-id=485%3A4924

**Comment by imvinay84** [comment]
Branch: `disappear_message`
https://github.com/fetchai/fetch-wallet/tree/disappear_message
