### ISSUE TITLE
ERC 20 to Native FET Bridge not working

### ISSUE THREAD

**Issue by jesseb24** [fetchai/fetch-wallet#343]
When I bridged my ERC 20 FET to native FET, it was a success, but my native FET never showed up in my wallet.

**Comment by erikcmcneill** [comment]
Same happened to me and still waiting. It's been about 24 hours and the Native FET still haven't showed up. Did it ever show up for you jesseb24? Any recommendations anyone?

**Comment by agent-dominatrix** [comment]
@jesseb24 @erikcmcneill could you guys please share your Ethereum transaction hash from the bridge history page? Also let us know if the transaction is completed (share the transaction hash) or pending on the Fetch network side. You can check that out in the bridge history page as well. We will investigate the issue. Nothing to worry about, if your FETs are locked due to any issues, we can manually unlock/bridge it for you 🙂

**Comment by erikcmcneill** [comment]
My 4th transaction hash is 0x16b9412eed8fdf85e8f9330010585b61a2e212e300d03622708c4263b336540a. On the fetch network side it is showing still pending.

**Comment by erikcmcneill** [comment]
Sorry, *Eth transaction hash is 0x16b9412eed8fdf85e8f9330010585b61a2e212e300d03622708c4263b336540a.
![Image 12-17-23 at 9 04 PM](https://github.com/fetchai/fetch-wallet/assets/154094926/f837f813-db99-485c-87d6-366c1182203c)
![Uploading Image 12-17-23 at 9.04 PM.jpeg…]()
![Uploading Image 12-17-23 at 9.04 PM.jpeg…]()

**Comment by erikcmcneill** [comment]
Thanks for the response and let me know anything else you need...

**Comment by erikcmcneill** [comment]
@agent-dominatrix Eth transaction hash is 0x16b9412eed8fdf85e8f9330010585b61a2e212e300d03622708c4263b336540a.
![Image 12-17-23 at 9 04 PM](https://github.com/fetchai/fetch-wallet/assets/154094926/911b1b48-b891-4aa9-8861-4a49620b7a13)
[](url)
![Uploading Image 12-17-23 at 9.04 PM.jpeg…]()

**Comment by jesseb24** [comment]
@agent-dominatrix Hi, I just checked the transaction and it completely went through. It took more than 3 days, but it finally went through. It's good to see.  @erikcmcneill I hope yours goes through.  Hopefully it's just delayed.

**Comment by erikcmcneill** [comment]
Just showed up. Thanks for the help!

**Comment by erikcmcneill** [comment]
Just showed up. Thanks for the help! @agent-dominatrix @jesseb24
